### ISSUE TITLE
Dealing with Stale Element Exceptions

### ISSUE THREAD

**Issue by aftershock9** [ElSnoMan/from-scripting-to-framework#13]
I have been experimenting with the framework - its great. thank you for sharing it with the wider audience and providing it as part of the test automation framework.

One issue I have encountered is dealing with Stale Element Exceptions. I would like to update the Framework to account for this, but haven't had much luck. 

Based on a stackoverflow link, https://stackoverflow.com/questions/12967541/how-to-avoid-staleelementreferenceexception-in-selenium/41502474#41502474, they suggest you would need to declare a new webdriver instance and locate the element. However I am not sure how to achieve this with the framework, as the Driver is declared as static.

**Comment by ElSnoMan** [comment]
You'll have to give me an example because you should be able to easily handle anything like that. The framework is really flexible and I left it at a place where people could really take it where they need to go. Here's the Wait class with the `StaleElementReferenceException` being ignored.

```c#
public Wait(int waitSeconds)
    {
        _wait = new WebDriverWait(Driver.Current, TimeSpan.FromSeconds(waitSeconds))
        {
            PollingInterval = TimeSpan.FromMilliseconds(500)
        };

        _wait.IgnoreExceptionTypes(
            typeof(NoSuchElementException),
            typeof(ElementNotVisibleException),
            typeof(StaleElementReferenceException)
        );
}
```

Also, you _do_ have the ability to create WebDrivers as needed. That's the whole point of `DriverFactory.cs`.

**Comment by ElSnoMan** [comment]
I'd also like to make sure it's understood that the WebDriver is not static. `Driver` as a class is static, but it's a wrapper of the initialized WebDriver that is _not_ static. I went over this in `Chapter 5: Customizing WebDriver`.

Also, I don't see why you'd need to create a new WebDriver mid test. I don't think that's what you actually want to do haha. That would create a whole new browser and session. You already have access to `Driver.Wait()` and I even go over how to make your own `WaitConditions` as well.

Provide some examples and I'm sure we can figure it out :)

**Comment by aftershock9** [comment]
The issue I am experiencing:

- Login
- Input case number via the search case menu
- Press enter to perform search
- The page does a postback and displays the search results
- Click the case number to load the case

Clicking the case number is where the stale element exception occurs now and then. This is the code:

**Test code**
```
//8. Search for case number
Driver.Wait.Until(ExpectedConditions.ElementIsVisible(Pages.Inbox.Map.InboxGrid.FoundBy));
Pages.Inbox.SearchBizagiCase(caseNumber);

//9. Load case
Driver.Wait.Until(ExpectedConditions.ElementToBeClickable(Pages.Inbox.Map.BizagiCaseNumber.FoundBy));
Pages.Inbox.Map.BizagiCaseNumber.Click();
```

The stale element seems to occur when clicking the case number. How would I achieve the suggested solution to dealing with stale element exception in the stackoverflow article. From my understanding it seems you would need to relook for the element that has gone stale. 

Thank you Carlos for responding.

**Comment by ElSnoMan** [comment]
If you completed all chapters and challenges, then you should have this in `Driver.cs`:

```c#
public static Element FindElement(By by, string elementName)
{
    var element = Wait.Until(drvr => drvr.FindElement(by));
    return new Element(element, elementName)
    {
        FoundBy = by
    };
}
```

* `FindElement` will wait until the element is present in the DOM and then return it.
* `StaleElementReferenceException` means that the element _was_ found but it is no longer in the DOM.

This raises a few questions:

* Is it expected that the `BizagiCaseNumber` becomes stale aka was there and then disappears?
* Is the page or component "flickering"?
* Is the `Wait` throwing the stale exception or is the `.Click()` throwing it?
* Does the test pass when you're debugging it and stepping through?
* Have you talked to your devs about this?

I ask these questions because it sounds like your app is flaky, not the test.
In Step 9, you're waiting for the element to be clickable. Granted, you're doing it in an interesting way and not how the finished course does it, but it _looks_ like it should work.

Side Note: I'd be curious to see what happens if you remove the `Wait` in Step 9 (if you have all completed courses and challenges).

Potential Solutions?

1. If the staleness is expected, you can easily check for that. We actually did this in `WaitConditions.cs`

```c#
public static Func<IWebDriver, bool> ElementNotDisplayed(IWebElement element)
{
    bool condition(IWebDriver driver)
    {
        try
        {
            // element is in the DOM, but not displayed
            return !element.Displayed;
        }
        catch (StaleElementReferenceException)
        {
            // element is not in the DOM, still return true
            return true;
        }
    }
    return condition;
}
```

2. If it's "flickering", meaning that the element is displayed, and then it's not, but you are waiting for it to be displayed, then you are in trouble haha.
That's a sign of a flaky app or component and makes working around it more of a hack than anything. I always raise this as a testability bug!
However, I can understand that you want to work around this. This would be a case where you want to use a `Thread.Sleep()` anti-pattern.

* Wait for the element to initially be displayed
* Sleep for an arbitrary number of seconds (feels bad just typing this haha)
* Proceed with the `.Click()`

This _should_ work. If it doesn't, then there is a bigger issue, but seeing the `Thread.Sleep()` is a nice indicator that you had to use a workaround for this action.

> Usually you'll add a comment to explain to readers why you used an arbitrary sleep

**Comment by aftershock9** [comment]
You have given me lots to think about and try out with the test. 

Thank you for your time :)
